# Week 8 – Local LLM Inference

## Project Title
Running Large Language Models Locally Using Ollama

## Objective
- To understand the advantages of running LLMs locally.
- To install and configure Ollama.
- To interact with local LLMs using Python.
- To generate responses for prompts from different domains.
- To compare responses generated by different models.
- To save responses for future chatbot development.

## 2. Introduction to Local LLM Inference

Large Language Models (LLMs) can generate human-like text,
answer questions, explain concepts, and write programs.

Ollama allows us to download and run supported language models
on our local computer.

Local LLM inference can improve privacy, reduce dependence on
cloud APIs, and allow experimentation without paying for each
API request. However, local models still require sufficient
memory and computing resources.

In this project, we use Ollama and Python to generate responses
for prompts from different domains and compare model outputs.

## 3. Ollama Installation and Verification

Ollama was installed on the local Windows computer.

The following terminal commands are used to verify the
installation and check the available models:

- `ollama --version`
- `ollama list`

In [1]:
import subprocess

commands = [
    ["ollama", "--version"],
    ["ollama", "list"]
]

for command in commands:
    print("\nCommand:", " ".join(command))

    try:
        result = subprocess.run(
            command,
            capture_output=True,
            text=True,
            timeout=30
        )

        print(result.stdout)

        if result.stderr:
            print(result.stderr)

    except Exception as error:
        print("Error:", error)

Command: ollama --version
ollama version is 0.40.11


Command: ollama list
NAME               ID              SIZE      MODIFIED
gemma2:2b          8ccf136fdd52    1.6 GB    59 minutes ago
llama3.2:latest    a80c4f17acd5    2.0 GB    8 hours ago

## 4. Available Local Models

The local models used in this project are:

1. Llama 3.2
2. Gemma 2B

Llama 3.2 is used to generate responses for the initial
prompt dataset. Gemma 2B is used for comparison.

Both models are accessed through Ollama. Their response
quality, length, relevance, and accuracy are evaluated.

Note: The models must be downloaded before they can be used.

## 5. Python Library Import

The following Python libraries are used:

- pandas: To load and analyse CSV datasets.
- ollama: To communicate with the local language model.
- pathlib: To manage project file paths.
- IPython.display: To display results in the notebook.

In [1]:
import pandas as pd
from pathlib import Path
from ollama import chat
from IPython.display import display

print("Libraries imported successfully.")

Libraries imported successfully.

## 6. Loading the Prompt Dataset

The prompts.csv file contains ten prompts from different
domains, including education, healthcare, coding, travel,
business, environment, technology, science, problem solving,
and creative writing.

The dataset is loaded using pandas for further processing.

In [3]:
BASE_DIR = Path.cwd().parent

DATASET_DIR = BASE_DIR / "dataset"

PROMPTS_FILE = DATASET_DIR / "prompts.csv"
RESPONSES_FILE = DATASET_DIR / "llm_responses.csv"

prompts_df = pd.read_csv(
    PROMPTS_FILE,
    encoding="utf-8-sig"
)

print("Total prompts:", len(prompts_df))

display(prompts_df)

Total prompts: 10

,prompt_id,domain,prompt
0,P001,Education,Explain artificial intelligence in simple Engl...
1,P002,Healthcare,Explain three healthy habits that help people ...
2,P003,Coding,Write a Python program to check whether a numb...
3,P004,Travel,Suggest a two-day travel itinerary for Chennai...
4,P005,Business,Explain three ways a small business can attrac...
5,P006,Environment,Explain five simple ways to reduce food waste ...
6,P007,Technology,Explain the difference between RAM and ROM in ...
7,P008,Science,Explain how photosynthesis works in plants.
8,P009,Problem Solving,"A student has five subjects with marks 80, 75,..."
9,P010,Creative Writing,Write a short story of about 100 words about a...

## 7. Generating LLM Responses

The Ollama Python library connects to the local Llama 3.2 model.

Each prompt is sent to the model, and the generated response
is collected for analysis.

The responses are saved in llm_responses.csv for future use.

In [4]:
MODEL_NAME = "llama3.2"

results = []

for _, row in prompts_df.iterrows():

    prompt = row["prompt"]

    try:
        response = chat(
            model=MODEL_NAME,
            messages=[
                {
                    "role": "user",
                    "content": prompt
                }
            ]
        )

        answer = response.message.content

        results.append({
            "prompt_id": row["prompt_id"],
            "domain": row["domain"],
            "model": MODEL_NAME,
            "prompt": prompt,
            "response": answer,
            "response_word_count": len(answer.split()),
            "status": "Success"
        })

        print(f"Completed: {row['prompt_id']}")

    except Exception as error:
        results.append({
            "prompt_id": row["prompt_id"],
            "domain": row["domain"],
            "model": MODEL_NAME,
            "prompt": prompt,
            "response": "",
            "response_word_count": 0,
            "status": f"Error: {error}"
        })

        print(f"Failed: {row['prompt_id']} - {error}")

results_df = pd.DataFrame(results)

results_df.to_csv(
    RESPONSES_FILE,
    index=False,
    encoding="utf-8"
)

print("\nResponse generation completed.")

display(results_df)

Completed: P001
Completed: P002
Completed: P003
Completed: P004
Completed: P005
Completed: P006
Completed: P007
Completed: P008
Completed: P009
Completed: P010

Response generation completed.

,prompt_id,domain,model,prompt,response,response_word_count,status
0,P001,Education,llama3.2,Explain artificial intelligence in simple Engl...,Here are three points that explain artificial ...,193,Success
1,P002,Healthcare,llama3.2,Explain three healthy habits that help people ...,Here are three healthy habits that can help pe...,220,Success
2,P003,Coding,llama3.2,Write a Python program to check whether a numb...,def check_even_odd(num):\n if num % 2 == 0:...,24,Success
3,P004,Travel,llama3.2,Suggest a two-day travel itinerary for Chennai...,"Chennai, the cultural hub of Tamil Nadu, is a ...",463,Success
4,P005,Business,llama3.2,Explain three ways a small business can attrac...,Here are three ways a small business can attra...,308,Success
5,P006,Environment,llama3.2,Explain five simple ways to reduce food waste ...,Here are five simple ways to reduce food waste...,279,Success
6,P007,Technology,llama3.2,Explain the difference between RAM and ROM in ...,Imagine your brain and your computer's memory....,163,Success
7,P008,Science,llama3.2,Explain how photosynthesis works in plants.,"Photosynthesis is the process by which plants,...",360,Success
8,P009,Problem Solving,llama3.2,"A student has five subjects with marks 80, 75,...","To calculate the average, we need to add up al...",79,Success
9,P010,Creative Writing,llama3.2,Write a short story of about 100 words about a...,"As a computer science major, Emma had always b...",99,Success

## 8. Displaying and Analysing Results

The generated responses are analysed using pandas.

The analysis includes:
- The total number of prompts.
- The number of successful responses.
- The average response length.
- The number of responses for each domain.

In [5]:
# Display the generated responses
display(
    results_df[
        [
            "prompt_id",
            "domain",
            "response_word_count",
            "status"
        ]
    ]
)

# Count successful responses
successful = (
    results_df["status"] == "Success"
).sum()

print("Total prompts:", len(results_df))
print("Successful responses:", successful)
print("Failed responses:", len(results_df) - successful)

# Calculate average response length for successful responses
successful_df = results_df[
    results_df["status"] == "Success"
]

if not successful_df.empty:
    average_words = successful_df[
        "response_word_count"
    ].mean()

    print(
        "Average response length:",
        round(average_words, 2),
        "words"
    )

    print("\nResponses by domain:")

    display(
        successful_df.groupby("domain").size()
        .reset_index(name="number_of_responses")
    )

  prompt_id            domain  response_word_count   status
0      P001         Education                  193  Success
1      P002        Healthcare                  220  Success
2      P003            Coding                   24  Success
3      P004            Travel                  463  Success
4      P005          Business                  308  Success
5      P006       Environment                  279  Success
6      P007        Technology                  163  Success
7      P008           Science                  360  Success
8      P009   Problem Solving                   79  Success
9      P010  Creative Writing                   99  Success

Total prompts: 10
Successful responses: 10
Failed responses: 0
Average response length: 218.8 words

Responses by domain:

             domain  number_of_responses
0          Business                    1
1            Coding                    1
2  Creative Writing                    1
3         Education                    1
4       Environment                    1
5        Healthcare                    1
6   Problem Solving                    1
7           Science                    1
8        Technology                    1
9            Travel                    1

## 9. Comparing Llama and Gemma

Llama 3.2 and Gemma 2B are evaluated using the same ten prompts.

The comparison considers:

1. Response quality and clarity.
2. Response length.
3. Accuracy.
4. Relevance to the prompt.

Both models receive identical prompts to make the comparison
fairer. Their generated responses are saved in
response_comparison.csv.

Accuracy is assessed by checking the answers against
appropriate reference information. Response length alone
does not determine response quality.

In [6]:
COMPARISON_FILE = DATASET_DIR / "response_comparison.csv"

comparison_results = []

MODEL_NAMES = ["llama3.2", "gemma2:2b"]

for _, row in prompts_df.iterrows():

    prompt_id = row["prompt_id"]
    domain = row["domain"]
    prompt = row["prompt"]

    for model_name in MODEL_NAMES:

        try:
            response = chat(
                model=model_name,
                messages=[
                    {
                        "role": "user",
                        "content": prompt
                    }
                ]
            )

            answer = response.message.content

            comparison_results.append({
                "prompt_id": prompt_id,
                "domain": domain,
                "model": model_name,
                "prompt": prompt,
                "response": answer,
                "response_word_count": len(answer.split()),
                "status": "Success"
            })

            print(f"{model_name}: {prompt_id} completed")

        except Exception as error:

            comparison_results.append({
                "prompt_id": prompt_id,
                "domain": domain,
                "model": model_name,
                "prompt": prompt,
                "response": "",
                "response_word_count": 0,
                "status": f"Error: {error}"
            })

            print(f"{model_name}: {prompt_id} failed - {error}")


comparison_df = pd.DataFrame(comparison_results)

comparison_df.to_csv(
    COMPARISON_FILE,
    index=False,
    encoding="utf-8"
)

print("\nComparison dataset saved.")

display(
    comparison_df[
        [
            "prompt_id",
            "domain",
            "model",
            "response_word_count",
            "status"
        ]
    ]
)

llama3.2: P001 completed
gemma2:2b: P001 completed
llama3.2: P002 completed
gemma2:2b: P002 completed
llama3.2: P003 completed
gemma2:2b: P003 completed
llama3.2: P004 completed
gemma2:2b: P004 completed
llama3.2: P005 completed
gemma2:2b: P005 completed
llama3.2: P006 completed
gemma2:2b: P006 completed
llama3.2: P007 completed
gemma2:2b: P007 completed
llama3.2: P008 completed
gemma2:2b: P008 completed
llama3.2: P009 completed
gemma2:2b: P009 completed
llama3.2: P010 completed
gemma2:2b: P010 completed

Comparison dataset saved.

   prompt_id            domain      model  response_word_count   status
0       P001         Education   llama3.2                  133  Success
1       P001         Education  gemma2:2b                  115  Success
2       P002        Healthcare   llama3.2                  326  Success
3       P002        Healthcare  gemma2:2b                  288  Success
4       P003            Coding   llama3.2                  187  Success
5       P003            Coding  gemma2:2b                  210  Success
6       P004            Travel   llama3.2                  407  Success
7       P004            Travel  gemma2:2b                  370  Success
8       P005          Business   llama3.2                  280  Success
9       P005          Business  gemma2:2b                  357  Success
10      P006       Environment   llama3.2                  216  Success
11      P006       Environment  gemma2:2b                  188  Success
12      P007        Technology   llama3.2                  188  Success
13      P007        Technology  gemma2:2b                  174  Success
14      P008           Science   llama3.2                  382  Success
15      P008           Science  gemma2:2b                  425  Success
16      P009   Problem Solving   llama3.2                   72  Success
17      P009   Problem Solving  gemma2:2b                   46  Success
18      P010  Creative Writing   llama3.2                   95  Success
19      P010  Creative Writing  gemma2:2b                  107  Success

In [7]:
successful_comparisons = comparison_df[
    comparison_df["status"] == "Success"
]

summary = (
    successful_comparisons
    .groupby("model")
    .agg(
        successful_responses=("prompt_id", "count"),
        average_response_words=("response_word_count", "mean")
    )
    .reset_index()
)

summary["average_response_words"] = (
    summary["average_response_words"].round(2)
)

display(summary)

       model  successful_responses  average_response_words
0  gemma2:2b                    10                   228.0
1   llama3.2                    10                   228.6

## 10. Conclusion

This project demonstrates how to run Large Language Models
locally using Ollama and Python.

Ten prompts from different domains were used to generate
responses. The responses were saved in CSV files for
analysis and future chatbot development.

Llama 3.2 and Gemma 2B were compared using the same prompts.
Their response lengths, clarity, relevance, and accuracy
were considered during evaluation.

The project helped demonstrate local LLM inference, Python
integration, dataset handling, and model comparison.

The results can be used as a foundation for developing a
local chatbot in Week 9.